version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: test
    ports:
      - 5432:5432
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./csv-files:/var/lib/postgresql/csv-files

  postgres-auth:
    container_name: postgres-auth
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: test
    ports:
      - 5433:5432
    volumes:
    - ./auth.sql:/var/lib/postgresql/auth.sql
    - db-auth-data:/var/lib/postgresql/data
    
  
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
   
volumes:
  db-data:
    driver: local
  db-auth-data:
    driver: local
